version: '3.8'

services:
  backend:
    build: ./server
    container_name: casanostra_backend
    ports:
      - "3001:3001"
    restart: always

  frontend:
    build: ./client
    container_name: casanostra_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always